import { ShopifyProduct } from "yourders-types";

export const ShopifyCSVKeyValue: ShopifyProduct = {
  Handle: "Handle",
  Title: "Title",
  BodyHTML: "Body (HTML)",
  Vendor: "Vendor",
  ProductCategory: "Product Category",
  Type: "Type",
  Tags: "Tags",
  Published: "Published",
  Option1Name: "Option1 Name",
  Option1Value: "Option1 Value",
  Option2Name: "Option2 Name",
  Option2Value: "Option2 Value",
  Option3Name: "Option3 Name",
  Option3Value: "Option3 Value",
  VariantSKU: "Variant SKU",
  VariantGrams: "Variant Grams",
  VariantInventoryTracker: "Variant Inventory Tracker",
  VariantInventoryQty: "Variant Inventory Qty",
  VariantInventoryPolicy: "Variant Inventory Policy",
  VariantFulfillmentService: "Variant Fulfillment Service",
  VariantPrice: "Variant Price",
  VariantCompareAtPrice: "Variant Compare At Price",
  VariantRequiresShipping: "Variant Requires Shipping",
  VariantTaxable: "Variant Taxable",
  VariantBarcode: "Variant Barcode",
  ImageSrc: "Image Src",
  ImagePosition: "Image Position",
  ImageAltText: "Image Alt Text",
  GiftCard: "Gift Card",
  SEOTitle: "SEO Title",
  SEODescription: "SEO Description",
  GoogleShoppingGoogleProductCategory:
    "Google Shopping / Google Product Category",
  GoogleShoppingGender: "Google Shopping / Gender",
  GoogleShoppingAgeGroup: "Google Shopping / Age Group",
  GoogleShoppingMPN: "Google Shopping / MPN",
  GoogleShoppingCondition: "Google Shopping / Condition",
  GoogleShoppingCustomProduct: "Google Shopping / Custom Product",
  GoogleShoppingCustomLabel0: "Google Shopping / Custom Label 0",
  GoogleShoppingCustomLabel1: "Google Shopping / Custom Label 1",
  GoogleShoppingCustomLabel2: "Google Shopping / Custom Label 2",
  GoogleShoppingCustomLabel3: "Google Shopping / Custom Label 3",
  GoogleShoppingCustomLabel4: "Google Shopping / Custom Label 4",
  VariantImage: "Variant Image",
  VariantWeightUnit: "Variant Weight Unit",
  VariantTaxCode: "Variant Tax Code",
  CostPerItem: "Cost per item",
  IncludedIndia: "Included / India",
  PriceIndia: "Price / India",
  CompareAtPriceIndia: "Compare At Price / India",
  IncludedInternational: "Included / International",
  PriceInternational: "Price / International",
  CompareAtPriceInternational: "Compare At Price / International",
  Status: "Status",
};

export const productApiBase = "http://localhost:3001/api/ps/product";
